### ISSUE TITLE
How to mannualy create a dev_tasks.txt

### ISSUE THREAD

**Issue by LukeLIN-web** [yizhongw/Tk-Instruct#4]
I run `./scripts/train_tk_instruct.sh`
But it cannot find dev_task.txt
I wonder whether it is a must.
```
Traceback (most recent call last):
  File "src/run_s2s.py", line 581, in <module>
    main()
  File "src/run_s2s.py", line 317, in main
    max_num_instances_per_eval_task=data_args.max_num_instances_per_eval_task
  File "/opt/conda/lib/python3.7/site-packages/datasets/load.py", line 1699, in load_dataset
    use_auth_token=use_auth_token,
  File "/opt/conda/lib/python3.7/site-packages/datasets/builder.py", line 596, in download_and_prepare
    dl_manager=dl_manager, verify_infos=verify_infos, **download_and_prepare_kwargs
  File "/opt/conda/lib/python3.7/site-packages/datasets/builder.py", line 690, in _download_and_prepare
    ) from None
OSError: Cannot find data file.
Original error:
[Errno 2] No such file or directory: 'data/splits/default/dev_tasks.txt'
```

**Comment by yizhongw** [comment]
Hi @LukeLIN-web, yeah we didn't provide the official dev set because we are not sure what should be used for validation in this cross-task generalization setting. We have a suggestion [here](https://github.com/yizhongw/Tk-Instruct/blob/main/README.md#:~:text=Since%20Natural%20Instructions,categories%20for%20validation.) for creating the dev tasks. Basically, you can copy some tasks in `train_tasks.txt` to `dev_tasks.txt` and the code should work fine.

**Comment by LukeLIN-web** [comment]
I create `dev_tasks.txt` in data/splits/default/dev_tasks.txt. But it still has error :
 
Traceback (most recent call last):                                                                                                                                   
  File "src/run_s2s.py", line 591, in <module>                                                                                                                       
    main()                                                                                                                                                           
  File "src/run_s2s.py", line 497, in main                                                                                                                           
    train_result = trainer.train(resume_from_checkpoint=checkpoint)                                                                                                  
  File "/opt/conda/lib/python3.7/site-packages/transformers/trainer.py", line 1475, in train                                                                         
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)                                                                                
  File "/opt/conda/lib/python3.7/site-packages/transformers/trainer.py", line 1602, in _maybe_log_save_evaluate                                                      
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)                                                                                                        
  File "/opt/conda/lib/python3.7/site-packages/transformers/trainer_seq2seq.py", line 70, in evaluate                                                                
    return super().evaluate(eval_dataset, ignore_keys=ignore_keys, metric_key_prefix=metric_key_prefix)                                                              
  File "/opt/conda/lib/python3.7/site-packages/transformers/trainer.py", line 2253, in evaluate                                                                      
    eval_dataloader = self.get_eval_dataloader(eval_dataset)                                                                                                         
  File "/opt/conda/lib/python3.7/site-packages/transformers/trainer.py", line 738, in get_eval_dataloader                                                            
    raise ValueError("Trainer: evaluation requires an eval_dataset.")                                                                                                
ValueError: Trainer: evaluation requires an eval_dataset.

**Comment by yizhongw** [comment]
What is your running command? And what are included in your `dev_tasks.txt`?

**Comment by LukeLIN-web** [comment]
running command:
` ./scripts/train_tk_instruct.sh `

dev_task.txt
```
task1356_xlsum_title_generation
task893_gap_fill_the_blank_coreference_resolution
task641_esnli_classification
task1529_scitail1.1_classification
task202_mnli_contradiction_classification
task670_ambigqa_question_generation
task1393_superglue_copa_text_completion
task1344_glue_entailment_classification
task288_gigaword_summarization
task1387_anli_r3_entailment
task1664_winobias_text_generation
task1161_coda19_title_generation
task880_schema_guided_dstc8_classification
task738_perspectrum_classification
task1439_doqa_cooking_isanswerable
task645_summarization
task619_ohsumed_abstract_title_generation
task1728_web_nlg_data_to_text
task1640_aqa1.0_answerable_unanswerable_question_classification
```

```
{'loss': 1.8193, 'learning_rate': 5e-05, 'epoch': 0.17}
Traceback (most recent call last):
  File "src/run_s2s.py", line 591, in <module>
    main()
  File "src/run_s2s.py", line 497, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/opt/conda/lib/python3.7/site-packages/transformers/trainer.py", line 1475, in train
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/opt/conda/lib/python3.7/site-packages/transformers/trainer.py", line 1602, in _maybe_log_save_evaluate
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
  File "/opt/conda/lib/python3.7/site-packages/transformers/trainer_seq2seq.py", line 70, in evaluate
    return super().evaluate(eval_dataset, ignore_keys=ignore_keys, metric_key_prefix=metric_key_prefix)
  File "/opt/conda/lib/python3.7/site-packages/transformers/trainer.py", line 2253, in evaluate
    eval_dataloader = self.get_eval_dataloader(eval_dataset)
  File "/opt/conda/lib/python3.7/site-packages/transformers/trainer.py", line 738, in get_eval_dataloader
    raise ValueError("Trainer: evaluation requires an eval_dataset.")
ValueError: Trainer: evaluation requires an eval_dataset.
```

**Comment by yizhongw** [comment]
It's wired. Did you change anything in the script? If you have `dev_tasks.txt`, you should be able to load the `eval_dataset` here in this [line](https://github.com/yizhongw/Tk-Instruct/blob/91494f2c52fd694d6c47fd34d577778fb48212be/src/run_s2s.py#L409). Can you check if the `eval_dataset` is correct here?

**Comment by LukeLIN-web** [comment]
> It's wired. Did you change anything in the script? If you have `dev_tasks.txt`, you should be able to load the `eval_dataset` here in this [line](https://github.com/yizhongw/Tk-Instruct/blob/91494f2c52fd694d6c47fd34d577778fb48212be/src/run_s2s.py#L409). Can you check if the `eval_dataset` is correct here?

 I clone the newest repo src/ and scripts/ , it run smoothly.
